name: Build and deploy jobs

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    DOTNET_VERSION: "10.0"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Publish Function App
              working-directory: ./RemoveLinks
              run: |
                  dotnet restore
                  dotnet publish -c Release -o output

            - name: Verify publish output
              run: |
                  echo "Contents of RemoveLinks/output:"
                  ls -la ./RemoveLinks/output

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AD8B25AEC2F1422E96E491AB2031B79A }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AA0459BF05D842D69BDC432A5F279EDD }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_995144ED8CB34E35AE4C0894126857EF }}

            - name: Deploy Function App
              uses: Azure/functions-action@v1
              with:
                  app-name: urlshortenerjobs
                  slot-name: Production
                  package: ./RemoveLinks/output
